version: "3.9"

services:
  db_master:
    image: postgres:15
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: master123
      POSTGRES_DB: visitors_master
    volumes:
      - master_db_data:/var/lib/postgresql/data
    restart: always

  db_child:
    image: postgres:15
    environment:
      POSTGRES_USER: child
      POSTGRES_PASSWORD: child123
      POSTGRES_DB: visitors_child
    volumes:
      - child_db_data:/var/lib/postgresql/data
    restart: always

  master_server:
    build: ./master_server
    container_name: master_server
    environment:
      - DB_HOST=db_master
      - DB_NAME=visitors_master
      - DB_USER=master
      - DB_PASSWORD=master123
      - DJANGO_SECRET_KEY=dev-secret-master
    ports:
      - "8000:8000"
    depends_on:
      - db_master
    restart: always

  child_server:
    build: ./child_server
    container_name: child_server
    environment:
      - DB_HOST=db_child
      - DB_NAME=visitors_child
      - DB_USER=child
      - DB_PASSWORD=child123
      - MASTER_API_URL=http://master_server:8000/api/   # endpoint interne Docker
      - DJANGO_SECRET_KEY=dev-secret-child
    ports:
      - "8001:8000"
    depends_on:
      - db_child
      - master_server
    restart: always

volumes:
  master_db_data:
  child_db_data:
